custom:
  enable: true      # 选项：true | false
  # 选择是否修补自定义版本 QQ

  version_name: "9.1.31" # 自定义 QQ 的版本号，将显示在 Release 中
  QQ_download_link: "https://downv6.qq.com/qqweb/QQ_1/android_apk/Android_9.1.31_64.apk"
  # 自定义 QQ 版本下载链接（需要是直链）
  # 请自行检查输入的安装包链接是否为直链，也就是说输入的链接在浏览器打开后能够自动下载安装包，可百度或在 QQ 官网自行获取
  # 建议使用 Arm64 安装包，否则需手动更改 GitHub Action Workflow 配置文件中 QAuxiliary 的下载文件名后缀

LSPatch_repo: "LSPosed/LSPatch"
# 选择使用的 LSPatch 项目（需在 releases 中提供 .jar 文件）
# JingMatrix 维护的 LSPatch 分支已适配 Android 15，若在高版本遇到兼容性问题可考虑使用
# 将字符串 "LSPosed/LSPatch" 更改为 "JingMatrix/LSPatch" 即可（使用该分支产生的后果请自负）

modules:
  # --- 预设模块 ---
  # 将值设为 true 来启用模块，设为 false 则禁用
  QAuxiliary: true
  XAutoDaily: true
  TSBattery: true
  QQCleaner: true

  # --- 自定义模块 ---
  # 在下方列表中添加自定义模块，可以添加多个
  # 工作流将自动下载所有链接指向的模块，并提取文件名
  # 如需禁用，请将整个对象（从 '-' 开始）删除或用 '#' 注释掉
  custom:
    - name: "FunBox" # 模块的显示名称
      download_link: "https://github.com/Xposed-Modules-Repo/have.fun/releases/download/1067-v1067/FunBox_v1067.Apk"
    # - name: "Another Module"
    #   download_link: "https://example.com/another_module.apk"

latest:
  enable: true      # 选项：true | false
# 选择是否修补最新版 QQ
# 基于最新版 QQ 修补的版本，部分模块功能可能因为未适配而失效，请酌情使用

force: false        # 选项：true | false
# 选择是否忽略版本更新状态，强制进行修补（不推荐长期开启）
