name: Release

# 控制工作流何时运行
on:
  push:
    branches: [ "main" ]

  repository_dispatch:
    types: [new-release]

  # 允许手动运行工作流
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-8958:
    name: build v8.9.58
    runs-on: ubuntu-latest
    steps:
      # 下载LSPatch
      - name: Download LSPatch
        run: gh release download --repo LSPosed/LSPatch --pattern lspatch.jar

      # 下载待修补的应用
      - name: 下载QQ8.9.58
      # 官方直链  run: wget -O QQ8.9.58. https://downv6.qq.com/qqweb/QQ_1/android_apk/Android_8.9.58_64_HB2.apk
        run: gh release download -O QQ-8.9.58.apk --repo Hakuin123/MQGA READY --pattern QQ_8.9.58_64_HB2.apk

      # 使用GitHub CLI下载模块最新Release版本
      - name: 下载模块
        run: |
          gh release download -O QAuxiliary.apk --repo cinit/QAuxiliary     --pattern '*-arm64.apk'
          gh release download -O XAutoDaily.apk --repo LuckyPray/XAutoDaily --pattern '*.apk'
          gh release download -O TSBattery.apk  --repo fankes/TSBattery     --pattern 'app-release.apk'
          gh release download -O QQCleaner.apk  --repo KitsunePie/QQCleaner --pattern 'app-release.apk'

      # 修补
      - name: RUN
        run: java -jar lspatch.jar QQ-8.9.58.apk -m QAuxiliary.apk,XAutoDaily.apk,TSBattery.apk,QQCleaner.apk

      # 上传修补完成的文件
      #- name: 上传修补完成的文件
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: QQ-8.9.58-Release
      #    path: QQ-8.9.58-360-lspatched.apk

      # 提交Release以便下载
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: QQ-8.9.58-360-lspatched.apk
          tag_name: Release
          name: QQ Release
          body: 仅在此发布最新修补的Release版本




  
  build-latest:
    name: build latest version
    needs: build-8958
    runs-on: ubuntu-latest
    steps:
      - name: Download LSPatch
        run: gh release download --repo LSPosed/LSPatch --pattern lspatch.jar

      # 下载待修补的应用
      - name: 下载最新版QQ
      # 官方直链  run: wget -O QQ8.9.58. https://downv6.qq.com/qqweb/QQ_1/android_apk/Android_8.9.58_64_HB2.apk
      # 由于QQ官方未给出固定链接，故使用酷安提供下载（豌豆荚有固定链接但更新不及时）
        run: wget -O QQ-latest.apk 'https://dl.coolapk.com/down?pn=com.tencent.mobileqq&id=MzgzNA&h=aefedf55ryt58j'

      # 使用GitHub CLI下载模块最新Release版本
      - name: 下载模块
        run: |
          gh release download -O QAuxiliary.apk --repo cinit/QAuxiliary     --pattern '*-arm64.apk'
          gh release download -O XAutoDaily.apk --repo LuckyPray/XAutoDaily --pattern '*.apk'
          gh release download -O TSBattery.apk  --repo fankes/TSBattery     --pattern 'app-release.apk'
          gh release download -O QQCleaner.apk  --repo KitsunePie/QQCleaner --pattern 'app-release.apk'

      # 修补
      - name: RUN
        run: java -jar lspatch.jar QQ-latest.apk -m QAuxiliary.apk,XAutoDaily.apk,TSBattery.apk,QQCleaner.apk

      # 提交Release以便下载
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: QQ-latest-360-lspatched.apk
          tag_name: Release
          name: QQ Release
          body: 仅在此发布最新修补的Release版本