# This is a basic workflow to help you get started with Actions

name: Releases

# 控制工作流何时运行
on:
  repository_dispatch:
    types: [new-release]

  # 允许手动运行工作流
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 下载LSPatch
      - name: Download LSPatch
        run: wget https://github.com/LSPosed/LSPatch/releases/latest/download/lspatch.jar

      # 下载待修补的应用
      - name: 下载待修补的应用
      # 官方直链  run: wget -O QQ8.9.58. https://downv6.qq.com/qqweb/QQ_1/android_apk/Android_8.9.58_64_HB2.apk
        run: wget -O QQ8.9.58.apk https://github.com/Hakuin123/MQGA/releases/download/READY/QQ_8.9.58_64_HB2.apk

      # 使用GitHub CLI下载模块最新版本
      - name: 下载模块
        run: |
          gh release download -O QAuxiliary.apk --repo cinit/QAuxiliary     --pattern '*-arm64.apk'
          gh release download -O XAutoDaily.apk --repo LuckyPray/XAutoDaily --pattern '*.apk'
          gh release download -O TSBattery.apk  --repo fankes/TSBattery     --pattern 'app-release.apk'
          gh release download -O QQCleaner.apk  --repo KitsunePie/QQCleaner --pattern 'app-release.apk'

      # 修补
      - name: RUN
        run: java -jar lspatch.jar QQ8.9.58.apk -m QAuxiliary.apk,XAutoDaily.apk,QAuxiliary.apk,TSBattery.apk,QQCleaner.apk


      # 上传修补完成的文件
      - name: 上传修补完成的文件
        uses: actions/upload-artifact@v3
        with:
          name: QQ8.9.58-360-lspatched.apk
          path: QQ8.9.58-360-lspatched.apk
