# This is a basic workflow to help you get started with Actions

name: Release

# 控制工作流何时运行
on:
  repository_dispatch:
    types: [new-release]

  # 允许手动运行工作流
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 下载LSPatch
      - name: Download LSPatch
        run: gh release download --repo LSPosed/LSPatch --pattern lspatch.jar
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 下载待修补的应用
      - name: 下载待修补的应用
      # 官方直链  run: wget -O QQ8.9.58. https://downv6.qq.com/qqweb/QQ_1/android_apk/Android_8.9.58_64_HB2.apk
        run: gh release download -O QQ-8.9.58.apk --repo Hakuin123/MQGA READY --pattern QQ_8.9.58_64_HB2.apk
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 使用GitHub CLI下载模块最新Release版本
      - name: 下载模块
        run: |
          gh release download -O QAuxiliary.apk --repo cinit/QAuxiliary     --pattern '*-arm64.apk'
          gh release download -O XAutoDaily.apk --repo LuckyPray/XAutoDaily --pattern '*.apk'
          gh release download -O TSBattery.apk  --repo fankes/TSBattery     --pattern 'app-release.apk'
          gh release download -O QQCleaner.apk  --repo KitsunePie/QQCleaner --pattern 'app-release.apk'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 修补
      - name: RUN
        run: java -jar lspatch.jar QQ-8.9.58.apk -m QAuxiliary.apk,XAutoDaily.apk,TSBattery.apk,QQCleaner.apk


      # 上传修补完成的文件
      #- name: 上传修补完成的文件
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: QQ-8.9.58-Release
      #    path: QQ-8.9.58-360-lspatched.apk

      # 提交Release以便下载
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: QQ-8.9.58-360-lspatched.apk
          tag_name: Release
          name: QQ Release ${{GITHUB_RUN_ID}}
          
      - run: echo ${GITHUB_REF}