# This is a basic workflow to help you get started with Actions

name: Releases

# 控制工作流何时运行
on:
  repository_dispatch:
    types:
      - LSPosed_LSPatch_update
      - KitsunePie_QQCleaner_update
      - fankes_TSBattery_update
      - cinit_QAuxiliary_update
      - LuckyPray_XAutoDaily_update

  # 允许手动运行工作流
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 下载LSPatch
      - name: Download LSPatch
        run: wget https://github.com/LSPosed/LSPatch/releases/latest/download/lspatch.jar

      # 下载待修补的应用
      - name: 下载待修补的应用
      # 官方直链  run: wget -O QQ8.9.58. https://downv6.qq.com/qqweb/QQ_1/android_apk/Android_8.9.58_64_HB2.apk
        run: wget -O QQ8.9.58.apk https://github.com/Hakuin123/MQGA/releases/download/READY/QQ_8.9.58_64_HB2.apk

      # 下载模块
      - name: 下载模块
        run: |
          wget -O XAutoDaily.apk https://github.com/LuckyPray/XAutoDaily/releases/download/v3.0.19/XAutoDaily_3.0.19.apk
          wget -O QAuxiliary.apk https://github.com/cinit/QAuxiliary/releases/download/v1.4.2/QAuxv-v1.4.2.r1659.fd171b1-arm64.apk
          wget -O TSBattery.apk https://github.com/fankes/TSBattery/releases/latest/download/app-release.apk
          wget -O QQCleaner.apk https://github.com/KitsunePie/QQCleaner/releases/latest/download/app-release.apk

      # 修补
      - name: RUN
        run: java -jar lspatch.jar QQ8.9.58.apk -m XAutoDaily.apk -m QAuxiliary.apk -m TSBattery.apk -m QQCleaner.apk


      # 上传修补完成的文件
      - name: 上传修补完成的文件
        uses: actions/upload-artifact@v3
        with:
          name: QQ8.9.58-360-lspatched.apk
          path: QQ8.9.58-360-lspatched.apk
