on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  load-config:
    runs-on: ubuntu-latest
    steps:
      # 检出代码，确保能访问到配置文件
      - name: Checkout repository
        uses: actions/checkout@v4

      # 安装 yq（YAML 处理器）
      - name: Install yq
        run: |
            apt list --installed
            dpkg -l

      # 读取配置并导出变量
      - name: Load YAML config
        id: config
        run: |

          # 提取复杂值并转换为 JSON
          yq -o=json app-config.yml > config.json
          echo "config_json=$(cat config.json | jq -c)" >> $GITHUB_ENV

      # 使用配置的值
      - name: Use config values
        run: |
          echo "Full Config: ${{ env.config_json.how }}"