name: YAML to Env Example Workflow

on:

    
  # 仅供测试：每次提交时运行工作流
  push:
    branches: ["main"]



jobs:
  yaml-to-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set ENV values from YAML
        uses: dcarbone/yaml-to-env-action@v3
        with:
          yaml-file: config.yml

      - name: Print environment variables
        run: |
          printenv