name: Dynamic Workflow Control with YAML

on: [push]

jobs:
  dynamic-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up yq
      uses: mikefarah/yq/setup@v4
      
    - name: Parse YAML and export to environment
      id: parse_yaml
      run: |
        # 读取整个YAML文件并解析为JSON
        json=$(yq e 'to_entries | map({(.key): .value}) | add' config.yaml)
        
        # 将JSON对象转换为环境变量格式
        echo "$json" | jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' >> $GITHUB_ENV
      
    - name: Conditional step (controlled by YAML)
      if: ${{ fromJSON(env.enable_step) }}
      run: |
        echo "This step is enabled based on the YAML configuration."
        echo "The message from config.yaml is: $MESSAGE"
        echo "Another variable from config.yaml is: $ANOTHER_VAR"
        
    - name: Output environment variable
      run: |
        echo "Outputting environment variables:"
        echo "MESSAGE=$MESSAGE"
        echo "ANOTHER_VAR=$ANOTHER_VAR"
